proc test03-timer_lambda_py {} {
    puts "\nTEST: TIMER LAMBDA PYTHON"
    send "python3 ros2 run examples_rclcpp_minimal_timer timer_lambda\r"
    expect -exact {Hello, world!}
    expect -exact {Hello, world!}
    expect -exact {Hello, world!}
    expect -exact {Hello, world!}
    expect -exact {Hello, world!}
    send_ctrl_c
    expect -exact {[vxWorks}
    send "rtp delete /usr/lib/examples_rclcpp_minimal_timer/timer_lambda"
}
