proc test-sros2_talker_py {} {
    send "set env \"ROS_SECURITY_ENABLE=true\"\r"
    expect -exact {[vxWorks}
    send "python3 ros2 run demo_nodes_cpp talker --ros-args --enclave /talker_listener/talker\r"
    expect -exact {Found security directory}
    expect -exact {Publishing}
    expect -exact {Publishing}
    expect -exact {Publishing}
    expect -exact {Publishing}
    send_ctrl_c
    expect -exact {[vxWorks}
    send "set env \"ROS_SECURITY_ENABLE=false\"\r"
    expect -exact {[vxWorks}
    send "rtp delete /usr/lib/demo_nodes_cpp/talker"
}
