# common-ros2-native.inc project specific include file for the shell scripts
#
# Copyright (c) 2019 Wind River Systems, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Modification history
# --------------------
# 12apr19,akh  created


PRJ_NATIVE_GIT_REPO="https://github.com/Wind-River/vxworks7-layer-for-ros2.git"
PRJ_NATIVE_GIT_BRANCH="master"
PRJ_NATIVE_GIT_DIR="${WIND_PKGS_DIR_NAME}/middleware"

