name: Mirror master to dashing-releases

on:
  push:
    branches: [ master ]

jobs:
  mirror-master-to-dashing:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror to "dashing-release-SR0640"
      uses: zofrex/mirror-branch@v1
      with:
        target-branch: dashing-release-SR0640
    - name: Mirror to "dashing-release-22.03"
      uses: zofrex/mirror-branch@v1
      with:
        target-branch: dashing-release-22.03
