name: Mirror master to supported ROS 2 releases

on:
  push:
    branches: [ master ]

jobs:
  mirror-master-to-supported-releases:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror to "humble-release-23.03"
      uses: zofrex/mirror-branch@v1
      with:
        target-branch: humble-release-23.03
    - name: Mirror to "iron-release-23.03"
      uses: zofrex/mirror-branch@v1
      with:
        target-branch: iron-release-23.03
