name: A Single VxWorks ROS 2 Build

on:
  workflow_dispatch:
    inputs:
      json_file_name:
        description: 'Build Config JSON File'
        required: true
        default: 'vxros2build-qemu.json'
      ros_distro:
        description: 'ROS distribution'
        required: true
        default: 'humble'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger VxWorks ROS 2 ${{ github.event.inputs.ros_distro }} build
        uses: ./.github/workflows/vxworks-ros2-build.yml
        with:
          json_file_name: ${{ github.event.inputs.json_file_name }}
          ros_distro: ${{ github.event.inputs.ros_distro }}
