name: A Single VxWorks ROS 2 Build

on:
  workflow_dispatch:
    inputs:
      json_file_name:
        description: 'Build Config JSON File'
        required: true
        default: 'vxros2build-qemu.json'
      ros_distro:
        description: 'ROS distribution'
        required: true
        default: 'humble'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger VxWorks ROS 2 ${{ github.event.inputs.ros_distro }} build
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '77241288',
              ref: 'refs/heads/two-workflows', // Corrected quote usage here
              inputs: {
                json_file_name: 'vxros2build-qemu.json',
                ros_distro: 'humble'
              }
            });
